### ISSUE TITLE
Erreur 500 lors du décalage des voeux

### ISSUE THREAD

**Issue by NicosOu** [CaraGk/gesseh#176]
si je souhaite monter ou descendre un voeux s'affiche : Le serveur a retourné une erreur "500 Internal Server Error".
https://tours.kryptadia.org/simulation/6313/up?simid=26

**Comment by CaraGk** [comment]
Mon analyse du bug :
- Il n'y avait pas de période de simulation de défini (ou plutôt d'active) au moment du test
- ET un admin surcharge les vœux d'un étudiant
Dans tous les autres cas de figure, le bug n'est pas reproductible.

Il est lié à `$period = $this->em->getRepository('GessehSimulationBundle:SimulPeriod')->getActive()->getPeriod()`

**Comment by CaraGk** [comment]
Mon analyse du bug :
- Il n'y avait pas de période de simulation de défini (ou plutôt d'active) au moment du test
- ET un admin surcharge les vœux d'un étudiant
Dans tous les autres cas de figure, le bug n'est pas reproductible.

Il est lié à `$period = $this->em->getRepository('GessehSimulationBundle:SimulPeriod')->getActive()->getPeriod()`
